--1
CREATE PROCEDURE DSMonhoc
    @TenSv NVARCHAR(50)
AS
BEGIN
    SELECT DISTINCT MaMon FROM DangKyHoc dkh
	left join SinhVien sv on sv.MaSV = dkh.MaSV
	WHERE sv.HoTen = @TenSv;
END;
--2
CREATE PROC DSSINHVIEN
	@TENMONHOC NVARCHAR(20)
AS
BEGIN
	SELECT HOTEN FROM SinhVien SV
	LEFT JOIN DangKyHoc DKH ON SV.MaSV = DKH.MaSV
	LEFT JOIN MonHoc MH ON MH.MaMon = DKH.MaMon
	WHERE @TENMONHOC = MH.TenMon
END;
--3
CREATE VIEW DSSINHVIENTHEOKHOA AS
SELECT MaSV,HoTen,NgaySinh,TENKHOA  FROM SinhVien
LEFT JOIN Khoa ON KHOA.MaKhoa = SinhVien.MaKhoa
--4
CREATE FUNCTION [dbo].SOLUONGSV (@TENKHOA NVARCHAR(20) = N'Công nghệ thông tin')
RETURNs INT
AS 
BEGIN
DECLARE @SL INT;
SELECT @SL = COUNT(MaSV) FROM SinhVien
LEFT JOIN Khoa K ON SinhVien.MaKhoa = K.MaKhoa
WHERE K.TenKhoa = @TENKHOA;
RETURN (@SL);
ENd
--5
SELECT TOP 2 MaSV,COUNT(MaMon) AS SOMONDANGKY
FROM DangKyHoc 
GROUP BY MaSV
ORDER BY SOMONDANGKY
--7
CREATE PROC TONGSOTINCHI
	@MASINHVIEN CHAR(8),
	@HOCKI SMALLINT,
	@TONGSO SMALLINT OUTPUT
AS 
BEGIN
	SELECT  @TONGSO = SUM(SOTINCHI) FROM DangKyHoc DKH
	LEFT JOIN MonHoc MH ON DKH.MaMon = MH.MaMon
	WHERE MaSV = @MASINHVIEN AND HocKy = @HOCKI
	GROUP BY MaSV
END
--8
CREATE PROC DANHSACHSV 
	@HOCKY SMALLINT
AS
BEGIN
	SELECT MASV,SUM(SOTINCHI) AS TONGTINDANGKY FROM DangKyHoc DKH
	LEFT JOIN MonHoc MH ON DKH.MaMon = MH.MaMon
	WHERE HocKy = @HOCKY
	GROUP BY MaSV
	HAVING SUM(SoTinChi) > 2
END

--9
CREATE PROC INSERTDATA
	@MSV CHAR(8),
	@NAM1 SMALLINT = 0,
	@NAM2 SMALLINT = 0,
	@NAM3 SMALLINT = 0,
	@NAM4 SMALLINT = 0,
	@NAM5 SMALLINT = 0,
	@TONG SMALLINT = 0
AS
BEGIN
	SET @TONG = @NAM1 + @NAM2 + @NAM3 + @NAM4 + @NAM5
	INSERT INTO ThongKe
	VALUES (@MSV,@NAM1,@NAM2,@NAM3,@NAM4,@NAM5,@TONG)
END

--10
CREATE PROC INSERTTOSV
	@MSV CHAR(8),
	@HOTEN NVARCHAR(50) = '',
	@NGAYSINH DATETIME = '2000-1-1',
	@MAKHOA CHAR(4)
AS 
BEGIN
	 IF @MSV != ALL(SELECT MASV FROM SinhVien)
	 BEGIN
	 INSERT INTO SinhVien
	 VALUES (@MSV,@HOTEN,@NGAYSINH,@MAKHOA)
	 PRINT 'THEM THONG TIN SINH VIEN THANH CONG'
	 END
	 ELSE
	 BEGIN
	 PRINT 'DA CO SINH VIEN NAY TRONG HE THONG'
	 END
END

CREATE PROC DELETESINHVIEN
	@MSV CHAR(8)
AS
BEGIN
	IF @MSV != ALL(SELECT MASV FROM DangKyHoc)
	BEGIN
	DELETE FROM SinhVien WHERE MaSV = @MSV
	PRINT 'XOA SINH VIEN THANH CONG'
	END
	ELSE
	BEGIN
	PRINT 'KHONG THE XOA SINH VIEN NAY' 
	END
END

--11
CREATE TRIGGER THONGBAO ON MONHOC
AFTER DELETE
AS
BEGIN
	PRINT 'MOT MON HOC DA DUOC XOA KHOI BANG MON HOC';
END
--12
CREATE TRIGGER CAUHOI12 ON DANGKYHOC
FOR INSERT
AS
BEGIN
	IF (SELECT HOCKY FROM inserted) > 10 OR (SELECT HOCKY FROM inserted) < 0
	BEGIN 
	ROLLBACK TRAN
	PRINT 'KHONG THE THEM THONG TIN' 
	END
END
--13
CREATE TRIGGER CAUHOI13 ON DANGKYHOC
FOR INSERT
AS
BEGIN
	IF (SELECT MAMON FROM inserted) != ALL(SELECT MAMON FROM MonHoc)
	BEGIN
		ROLLBACK TRAN
		PRINT 'KHONG THE THEM'
	END
END
--14
CREATE TRIGGER CAUHOI14 ON MONHOC
AFTER DELETE
AS
BEGIN
	IF (SELECT MAMON FROM DangKyHoc) = (SELECT MAMON FROM deleted)
	BEGIN
	ROLLBACK TRAN
	PRINT 'KHONG THE XOA'
	END
END
--15
CREATE TRIGGER CAUHOI15 ON LOP
AFTER DELETE
AS
BEGIN
	DELETE FROM SINHVIEN
	WHERE MALOP = (SELECT MALOP FROM deleted)
END
